### ISSUE TITLE
Using mybinder for jupyter notebooks

### ISSUE THREAD

**Issue by mvdoc** [gallantlab/voxelwise_tutorials#1]
Now that you added the Jupyter notebooks, we could explore https://mybinder.org/ to see if it's worth providing an interactive version.

An alternative could be to host the notebooks on google colab and share the link.

I don't think this is a high priority, but just something to consider.

**Comment by TomDLT** [comment]
The tutorials are available on [Google colab](https://colab.research.google.com/github/gallantlab/voxelwise_tutorials/blob/main/tutorials/notebooks/movies_3T/merged_for_colab.ipynb).
