### ISSUE TITLE
delayers on multikernel RR

### ISSUE THREAD

**Issue by yibeichan** [gallantlab/voxelwise_tutorials#27]
Hello hello @mvdoc, I was doing multikernel RR and trying to put delayers in the pipeline, but it didn't work (the pipeline couldn't run with delayers). Is it that we don't need to set it up for multikernel RR or it's just not implemented yet. 

Also, I guess I don't fully (statistically) understand the delayer. Is it something similar to FIR? I noticed that in your tutorial, there was no HRF running on the stimulus side before fitting into RR. Is it because we have this delayer so we don't need to do any convolving anymore? (ping @jsmentch, since he has similar questions)

Thank you!

**Comment by mvdoc** [comment]
Hello hello @yibeichan!

Yep, we implement the FIR with the delayer. So there is no need to convolve the features by a standard HRF. (You could do that if you want, but then it would be fixed for every voxel, and the model prediction accuracy may be worse.) The fourth tutorial tries to get at that, showing that a model with delays is better than a model without delays, and showing that the FIR can model the HRF independently for each voxel (https://gallantlab.org/voxelwise_tutorials/_auto_examples/shortclips/04_plot_hemodynamic_response.html).

The delayer works with the multiple kernel ridge regression, as shown in the last tutorial. The set up is only a bit more complicated as it needs a ColumnKernelizer object in the pipeline. See https://gallantlab.org/voxelwise_tutorials/_auto_examples/shortclips/06_plot_banded_ridge_model.html

**Comment by yibeichan** [comment]
thank you thank you!! This makes a lot of sense!! I played with the multiple kernel RR two months ago, probably didn't find the example by that time. Today jeff and I had a conversation on delayer. Very glad we asked you!!
